version: '3'
services:
    php-apache:
        container_name: php-apache
        build: .
        volumes:
            - ./:/var/www/html/
        ports:
            - 8232:80
    composer:
        image: composer
        volumes:
            - ./:/app
        command: install --ignore-platform-reqs
